version: '3'

services:
  app:
    container_name: 'api-gateway-pompeeva'
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    network_mode: "host"
    ports:
      - '28081:8081'
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - PYTHONPATH=/workspace/src

